///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("2cb7e7ec-09ab-4cc9-b887-e81e863c491e", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRepository repository.
        /// </summary>
        public static TestRepository repo = TestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\7D Surgical System\\Applications\\Spine\\SD.Spine.Application.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\7D Surgical System\\Applications\\Spine\\SD.Spine.Application.exe", "", "C:\\7D Surgical System\\Applications\\Spine", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PatientDataWindow.LoadButton' at 39;9.", repo.PatientDataWindow.LoadButtonInfo, new RecordItemIndex(1));
            repo.PatientDataWindow.LoadButton.Click("39;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton' at 117;20.", repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButtonInfo, new RecordItemIndex(2));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton.Click("117;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.SomeContainer' at 527;607.", repo.Form7DSurgicalSoftwareSpineModule.SomeContainerInfo, new RecordItemIndex(3));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer.Click("527;607");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.SomeContainer' at 569;614.", repo.Form7DSurgicalSoftwareSpineModule.SomeContainerInfo, new RecordItemIndex(4));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer.Click("569;614");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.SomeContainer' at 607;608.", repo.Form7DSurgicalSoftwareSpineModule.SomeContainerInfo, new RecordItemIndex(5));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer.Click("607;608");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton1' at 158;24.", repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton1Info, new RecordItemIndex(6));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton1.Click("158;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for the attribute 'Enabled' to equal the specified value 'true'. Associated repository item: 'ManageTools.Label'", repo.ManageTools.LabelInfo, new RecordItemIndex(7));
            repo.ManageTools.LabelInfo.WaitForAttributeEqual(10000, "Enabled", "true");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ManageTools.SomeButton' at 60;14.", repo.ManageTools.SomeButtonInfo, new RecordItemIndex(8));
            repo.ManageTools.SomeButton.Click("60;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.CenterPedal' at 16;6.", repo.Form7DSurgicalSoftwareSpineModule.CenterPedalInfo, new RecordItemIndex(9));
            repo.Form7DSurgicalSoftwareSpineModule.CenterPedal.Click("16;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 24;31.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(10));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.Click("24;31");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Enabled' to equal the specified value 'true'. Associated repository item: 'Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton1'", repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton1Info, new RecordItemIndex(11));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.WorkflowButton1Info.WaitForAttributeEqual(5000, "Enabled", "true");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 42;26.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(12));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.Click("42;26");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 26;25.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(13));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.Click("26;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 26;25.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(14));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.Click("26;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 26;25.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(15));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.Click("26;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.CenterPedal' at 17;9.", repo.Form7DSurgicalSoftwareSpineModule.CenterPedalInfo, new RecordItemIndex(16));
            repo.Form7DSurgicalSoftwareSpineModule.CenterPedal.Click("17;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 32;30.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(17));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.Click("32;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 25;31.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(18));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.MoveTo("25;31");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 25;31.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(19));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.MoveTo("25;31");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 25;31.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(20));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.MoveTo("25;31");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Form7DSurgicalSoftwareSpineModule.LeftPedal' at 25;31.", repo.Form7DSurgicalSoftwareSpineModule.LeftPedalInfo, new RecordItemIndex(21));
            repo.Form7DSurgicalSoftwareSpineModule.LeftPedal.MoveTo("25;31");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form7DSurgicalSoftwareSpineModule.SomeContainer1.ExitButton' at 24;17.", repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.ExitButtonInfo, new RecordItemIndex(22));
            repo.Form7DSurgicalSoftwareSpineModule.SomeContainer1.ExitButton.Click("24;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SDSpineApplication.Option1Button' at 57;13.", repo.SDSpineApplication.Option1ButtonInfo, new RecordItemIndex(23));
            repo.SDSpineApplication.Option1Button.Click("57;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
