///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("d48e4472-0649-4b8e-8d50-8058b6a65c38")]
    public partial class TestRepository : RepoGenBaseFolder
    {
        static TestRepository instance = new TestRepository();
        TestRepositoryFolders.PatientDataWindowAppFolder _patientdatawindow;
        TestRepositoryFolders.Form7DSurgicalSoftwareSpineModuleAppFolder _form7dsurgicalsoftwarespinemodule;
        TestRepositoryFolders.ManageToolsAppFolder _managetools;
        TestRepositoryFolders.SDSpineApplicationAppFolder _sdspineapplication;

        /// <summary>
        /// Gets the singleton class instance representing the TestRepository element repository.
        /// </summary>
        [RepositoryFolder("d48e4472-0649-4b8e-8d50-8058b6a65c38")]
        public static TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRepository() 
            : base("TestRepository", "/", null, 0, false, "d48e4472-0649-4b8e-8d50-8058b6a65c38", ".\\RepositoryImages\\TestRepositoryd48e4472.rximgres")
        {
            _patientdatawindow = new TestRepositoryFolders.PatientDataWindowAppFolder(this);
            _form7dsurgicalsoftwarespinemodule = new TestRepositoryFolders.Form7DSurgicalSoftwareSpineModuleAppFolder(this);
            _managetools = new TestRepositoryFolders.ManageToolsAppFolder(this);
            _sdspineapplication = new TestRepositoryFolders.SDSpineApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d48e4472-0649-4b8e-8d50-8058b6a65c38")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PatientDataWindow folder.
        /// </summary>
        [RepositoryFolder("857656d2-8dbc-464b-900f-4dd46f4e06a9")]
        public virtual TestRepositoryFolders.PatientDataWindowAppFolder PatientDataWindow
        {
            get { return _patientdatawindow; }
        }

        /// <summary>
        /// The Form7DSurgicalSoftwareSpineModule folder.
        /// </summary>
        [RepositoryFolder("4c95bb7c-7e66-4931-8ff1-eacaa6d9690f")]
        public virtual TestRepositoryFolders.Form7DSurgicalSoftwareSpineModuleAppFolder Form7DSurgicalSoftwareSpineModule
        {
            get { return _form7dsurgicalsoftwarespinemodule; }
        }

        /// <summary>
        /// The ManageTools folder.
        /// </summary>
        [RepositoryFolder("acf79469-8194-42f0-8ed3-d173ae6f64fe")]
        public virtual TestRepositoryFolders.ManageToolsAppFolder ManageTools
        {
            get { return _managetools; }
        }

        /// <summary>
        /// The SDSpineApplication folder.
        /// </summary>
        [RepositoryFolder("48bc72fd-b7fd-4b17-ab57-ff46fef68503")]
        public virtual TestRepositoryFolders.SDSpineApplicationAppFolder SDSpineApplication
        {
            get { return _sdspineapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class TestRepositoryFolders
    {
        /// <summary>
        /// The PatientDataWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("857656d2-8dbc-464b-900f-4dd46f4e06a9")]
        public partial class PatientDataWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loadbuttonInfo;

            /// <summary>
            /// Creates a new PatientDataWindow  folder.
            /// </summary>
            public PatientDataWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PatientDataWindow", "/form[@automationid='PatientDataWindow']", parentFolder, 30000, null, true, "857656d2-8dbc-464b-900f-4dd46f4e06a9", "")
            {
                _loadbuttonInfo = new RepoItemInfo(this, "LoadButton", "container/container[2]/button[@automationid='LoadButton']", 30000, null, "92d2ae07-98c2-47bd-ab88-cdc415848601");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("857656d2-8dbc-464b-900f-4dd46f4e06a9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("857656d2-8dbc-464b-900f-4dd46f4e06a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoadButton item.
            /// </summary>
            [RepositoryItem("92d2ae07-98c2-47bd-ab88-cdc415848601")]
            public virtual Ranorex.Button LoadButton
            {
                get
                {
                    return _loadbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LoadButton item info.
            /// </summary>
            [RepositoryItemInfo("92d2ae07-98c2-47bd-ab88-cdc415848601")]
            public virtual RepoItemInfo LoadButtonInfo
            {
                get
                {
                    return _loadbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The Form7DSurgicalSoftwareSpineModuleAppFolder folder.
        /// </summary>
        [RepositoryFolder("4c95bb7c-7e66-4931-8ff1-eacaa6d9690f")]
        public partial class Form7DSurgicalSoftwareSpineModuleAppFolder : RepoGenBaseFolder
        {
            TestRepositoryFolders.SomeContainer1Folder _somecontainer1;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _centerpedalInfo;
            RepoItemInfo _leftpedalInfo;

            /// <summary>
            /// Creates a new Form7DSurgicalSoftwareSpineModule  folder.
            /// </summary>
            public Form7DSurgicalSoftwareSpineModuleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form7DSurgicalSoftwareSpineModule", "/form[@title~'^7D\\ Surgical\\ Software\\ -\\ Sp']", parentFolder, 30000, null, true, "4c95bb7c-7e66-4931-8ff1-eacaa6d9690f", "")
            {
                _somecontainer1 = new TestRepositoryFolders.SomeContainer1Folder(this);
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "?/?/container[@automationid='ViewingArea']/container[1]", 30000, null, "7888bf5a-8e12-4a61-a3d3-b7bcfc4c2d4a");
                _centerpedalInfo = new RepoItemInfo(this, "CenterPedal", "?/?/container[@automationid='FootPedalControl']/button[@automationid='CenterPedal']", 30000, null, "2b085b3b-dc12-4c67-a062-50f96d480661");
                _leftpedalInfo = new RepoItemInfo(this, "LeftPedal", "?/?/container[@automationid='FootPedalControl']/button[@automationid='LeftPedal']", 30000, null, "48be6713-42b8-4c10-8e96-afa5b84792d0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c95bb7c-7e66-4931-8ff1-eacaa6d9690f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c95bb7c-7e66-4931-8ff1-eacaa6d9690f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("7888bf5a-8e12-4a61-a3d3-b7bcfc4c2d4a")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("7888bf5a-8e12-4a61-a3d3-b7bcfc4c2d4a")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The CenterPedal item.
            /// </summary>
            [RepositoryItem("2b085b3b-dc12-4c67-a062-50f96d480661")]
            public virtual Ranorex.Button CenterPedal
            {
                get
                {
                    return _centerpedalInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CenterPedal item info.
            /// </summary>
            [RepositoryItemInfo("2b085b3b-dc12-4c67-a062-50f96d480661")]
            public virtual RepoItemInfo CenterPedalInfo
            {
                get
                {
                    return _centerpedalInfo;
                }
            }

            /// <summary>
            /// The LeftPedal item.
            /// </summary>
            [RepositoryItem("48be6713-42b8-4c10-8e96-afa5b84792d0")]
            public virtual Ranorex.Button LeftPedal
            {
                get
                {
                    return _leftpedalInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LeftPedal item info.
            /// </summary>
            [RepositoryItemInfo("48be6713-42b8-4c10-8e96-afa5b84792d0")]
            public virtual RepoItemInfo LeftPedalInfo
            {
                get
                {
                    return _leftpedalInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 folder.
            /// </summary>
            [RepositoryFolder("080cc576-d4f0-4942-832f-9f6ef200e1ac")]
            public virtual TestRepositoryFolders.SomeContainer1Folder SomeContainer1
            {
                get { return _somecontainer1; }
            }
        }

        /// <summary>
        /// The SomeContainer1Folder folder.
        /// </summary>
        [RepositoryFolder("080cc576-d4f0-4942-832f-9f6ef200e1ac")]
        public partial class SomeContainer1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _exitbuttonInfo;
            RepoItemInfo _workflowbuttonInfo;
            RepoItemInfo _workflowbutton1Info;

            /// <summary>
            /// Creates a new SomeContainer1  folder.
            /// </summary>
            public SomeContainer1Folder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer1", "container[1]", parentFolder, 30000, null, false, "080cc576-d4f0-4942-832f-9f6ef200e1ac", "")
            {
                _exitbuttonInfo = new RepoItemInfo(this, "ExitButton", "?/?/button[@automationid='ExitButton']", 30000, null, "3d8a46fc-3c09-44be-9a65-fd0a513b70c9");
                _workflowbuttonInfo = new RepoItemInfo(this, "WorkflowButton", "list/radiobutton[@name='WorkflowButton' and @text='Define Levels']", 30000, null, "acf0adc3-513d-4995-b406-e4358698976c");
                _workflowbutton1Info = new RepoItemInfo(this, "WorkflowButton1", "list[1]/radiobutton[@name='WorkflowButton' and @text='Register']", 30000, null, "3332bcb1-44aa-4f08-9ada-25962a5ec6e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("080cc576-d4f0-4942-832f-9f6ef200e1ac")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("080cc576-d4f0-4942-832f-9f6ef200e1ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExitButton item.
            /// </summary>
            [RepositoryItem("3d8a46fc-3c09-44be-9a65-fd0a513b70c9")]
            public virtual Ranorex.Button ExitButton
            {
                get
                {
                    return _exitbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ExitButton item info.
            /// </summary>
            [RepositoryItemInfo("3d8a46fc-3c09-44be-9a65-fd0a513b70c9")]
            public virtual RepoItemInfo ExitButtonInfo
            {
                get
                {
                    return _exitbuttonInfo;
                }
            }

            /// <summary>
            /// The WorkflowButton item.
            /// </summary>
            [RepositoryItem("acf0adc3-513d-4995-b406-e4358698976c")]
            public virtual Ranorex.RadioButton WorkflowButton
            {
                get
                {
                    return _workflowbuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The WorkflowButton item info.
            /// </summary>
            [RepositoryItemInfo("acf0adc3-513d-4995-b406-e4358698976c")]
            public virtual RepoItemInfo WorkflowButtonInfo
            {
                get
                {
                    return _workflowbuttonInfo;
                }
            }

            /// <summary>
            /// The WorkflowButton1 item.
            /// </summary>
            [RepositoryItem("3332bcb1-44aa-4f08-9ada-25962a5ec6e1")]
            public virtual Ranorex.RadioButton WorkflowButton1
            {
                get
                {
                    return _workflowbutton1Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The WorkflowButton1 item info.
            /// </summary>
            [RepositoryItemInfo("3332bcb1-44aa-4f08-9ada-25962a5ec6e1")]
            public virtual RepoItemInfo WorkflowButton1Info
            {
                get
                {
                    return _workflowbutton1Info;
                }
            }
        }

        /// <summary>
        /// The ManageToolsAppFolder folder.
        /// </summary>
        [RepositoryFolder("acf79469-8194-42f0-8ed3-d173ae6f64fe")]
        public partial class ManageToolsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _labelInfo;

            /// <summary>
            /// Creates a new ManageTools  folder.
            /// </summary>
            public ManageToolsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ManageTools", "/form[@title='Manage Tools']", parentFolder, 30000, null, true, "acf79469-8194-42f0-8ed3-d173ae6f64fe", "")
            {
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "container/container[@caption='']/button[1]", 30000, null, "f0712bba-64f0-4528-ba91-8abd3f762c3f");
                _labelInfo = new RepoItemInfo(this, "Label", "container/container[@caption='']/button[1]/text[@automationid='Label']", 30000, null, "b9d23eb2-760b-4d43-801e-a40da1f5adc1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("acf79469-8194-42f0-8ed3-d173ae6f64fe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("acf79469-8194-42f0-8ed3-d173ae6f64fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("f0712bba-64f0-4528-ba91-8abd3f762c3f")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("f0712bba-64f0-4528-ba91-8abd3f762c3f")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The Label item.
            /// </summary>
            [RepositoryItem("b9d23eb2-760b-4d43-801e-a40da1f5adc1")]
            public virtual Ranorex.Text Label
            {
                get
                {
                    return _labelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label item info.
            /// </summary>
            [RepositoryItemInfo("b9d23eb2-760b-4d43-801e-a40da1f5adc1")]
            public virtual RepoItemInfo LabelInfo
            {
                get
                {
                    return _labelInfo;
                }
            }
        }

        /// <summary>
        /// The SDSpineApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("48bc72fd-b7fd-4b17-ab57-ff46fef68503")]
        public partial class SDSpineApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _option1buttonInfo;

            /// <summary>
            /// Creates a new SDSpineApplication  folder.
            /// </summary>
            public SDSpineApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SDSpineApplication", "/form[@title='']", parentFolder, 30000, null, true, "48bc72fd-b7fd-4b17-ab57-ff46fef68503", "")
            {
                _option1buttonInfo = new RepoItemInfo(this, "Option1Button", "container[@caption='']/?/?/button[@automationid='Option1Button']", 30000, null, "38239ee0-5ccb-4582-8f97-5fb5035cfd4f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("48bc72fd-b7fd-4b17-ab57-ff46fef68503")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("48bc72fd-b7fd-4b17-ab57-ff46fef68503")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Option1Button item.
            /// </summary>
            [RepositoryItem("38239ee0-5ccb-4582-8f97-5fb5035cfd4f")]
            public virtual Ranorex.Button Option1Button
            {
                get
                {
                    return _option1buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Option1Button item info.
            /// </summary>
            [RepositoryItemInfo("38239ee0-5ccb-4582-8f97-5fb5035cfd4f")]
            public virtual RepoItemInfo Option1ButtonInfo
            {
                get
                {
                    return _option1buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}